#!/bin/sh
#
# ,run-qemu -- run a netbsd vm with qemu.
#
# command line flags and options:
#   -h | --help 	- print usage message and exit
#   -n 			- dry run: print the commands that would run but do not execute them
#   -v | --verbose 	- show actual commands being run
#   -c [nographic|curses|serial]
#   			- select console.  default: serial
#   --root-image file 	- use 'file' as root image
#   --root-size size 	- create root image with size 'size' e.g. 10g
#   --iso-image file 	- use 'file' as image for CD-ROM
#   -m | --mem size 	- allocate 'size" RAM to the VM
#   --ssh 		- forward localhost port 2022 to port 22 so ssh works
#   --fsdev dir[,(ro|rw}] - make directory 'dir' available via 9P, default: rw
#   -- 			- stop option processing and pass remaining arguments to qemu
#
# exit status:
#  - 1 for errors running commands or missing files/directories
#  - 2 for missing arguments to command line options
#  - 3 when 'usage' was invoked
#
set -eu

dryrun=
verbose=false
nbvers=10.1
memsz=2g
numcpu=2
pfx=vm
vmrootsz=10g
vmrootfile=${pfx}/netbsd-${nbvers}-root
isoimage=${pfx}/NetBSD-${nbvers}-amd64.iso
hostfwdssh=",hostfwd=tcp:127.1:2222-:22"
console="-display none -serial mon:stdio"
fsdev=""

case `uname -s` in
    Linux)
	accel=kvm
	;;
    Darwin)
	accel=hvf
	# QEMU 10.0.0 -smp N breaks netbsd for N!=1
	if [ $(uname -m) = x86_64 ] &&
	       qemu-img --version | fgrep 'version 10.0.0' >/dev/null 2>&1 ; then
	    numcpu=1
	fi
	;;
    NetBSD)
	accel=nvmm
	;;
    *)
	err 2 "unkown operating system. can't choose accellerator"
	;;
esac


usage() {
    cat 1>&2 <<EOF
usage: $0 [-h | --help ] [-n] [-v | --verbose] [-c [nographic|curses|serial]] [--root-image file] [--root-size sz] [--iso-image file] [[-m|--mem] size] [--ssh] [--fsdev dir[,ro|rw]]... [--] [ qemu-options]
EOF
    exit 3
}

err() {
    code=$1; shift
    echo 1>&2  "$@"
    exit ${code}
}

run() {
    ${verbose} && echo 1>&2 "$@"
    ${dryrun} "$@"
}

# parse args
while [ $# -ge 1 ]; do
    case "$1" in
	--)
	    shift; break	# no more options
	    ;;
	-h | --help)
	    usage		# exits
	    ;;
	-n)
	    dryrun=: ; shift
	    ;;
	-v | --verbose)
	    verbose=true; shift;
	    ;;
	-c)
	    shift
	    [ $# -ge 1 ] || err 2 "-c requires an argument (nographic|curses|serial)"
	    case $1 in
		nographic)
		    console="-nographic"
		    ;;
		curses)
		    console="-display curses"
		    ;;
		serial)
		    console="-display none -serial mon:stdio"
		    ;;
		*)
		    err 2 "unknown console option '$1'"
		    ;;
	    esac
	    shift
	    ;;
	--root-image)
	    shift
	    [ $# -ge 1 ] || err 2 "--root-image requires a file name argument"
	    vmrootfile=$1; shift
	    ;;
	--root-size)
	    shift
	    [ $# -ge 1 ] || err 2 "--root-size requires a size argument"
	    vmrootsz=$1; shift
	    ;;
	--iso-image)
	    shift
	    [ $# -ge 1 ] || err 2 "--iso-image requires a file name argument"
	    isoimage="$1"; shift
	    ;;
	-m | --mem)
	    shift
	    [ $# -ge 1 ] || err 2 "-m | --mem requires a size argument"
	    memsz=$1; shift
	    ;;
	--ssh)
	    shift
	    fwdssh=true
	    ;;
	--fsdev)
	    shift
	    [ $# -ge 1 ] || err 2 "-m | --fsdev requires a directory name"

	    roflag=$(expr "$1" : '.*,\(r[ow]\)$' || true)
	    case ${roflag:-rw} in # default to read-write as qemu does
		ro) roflag=",readonly=on";;
		rw) roflag=;;
	    esac

	    dir=$(echo "$1"| sed -e 's/,.*//') # strip everything from ',' on
	    [ ! -d "$dir" ] && err 1 "directory $dir doesn't exist"

	    shift

	    tag=$(basename "$dir")
	    fsdev="$fsdev -fsdev local,id=${tag},security_model=none,path=${dir}${roflag} -device virtio-9p-pci,fsdev=${tag},mount_tag=${tag}"
	    ;;
	*)
	    echo 1>&2 "unkown option: $1"
	    usage
	    ;;
    esac
done

qemucmd="qemu-system-x86_64 -M q35 -cpu host -accel $accel
    -smp ${numcpu} -m ${memsz}
    -device virtio-rng,rng=rng0
    -object rng-random,id=rng0,filename=/dev/urandom
    -nic user,model=virtio-net-pci${fwdssh:+$hostfwdssh}
    -drive if=ide,index=0,id=wd0,media=disk,file=${vmrootfile}
    -cdrom ${isoimage}
    ${fsdev}
    ${console}"

if [ ! -f ${vmrootfile} ]; then
    run qemu-img create -f qcow2 ${vmrootfile} ${vmrootsz} ||
	err 1 "error creating ${vmrootfile}: $?"
fi

run $qemucmd "$@"
